# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player_acct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotaPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo', models.IntegerField(default=500)),
                ('user_acct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dota_player', to='player_acct.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('is_disputed', models.BooleanField(default=False)),
                ('elo_modifier', models.IntegerField(default=25)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('elo', models.IntegerField(default=500)),
                ('players', models.ManyToManyField(related_name='teams', to='dota_mm.DotaPlayer')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='matches', to='dota_mm.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dota_mm.Team'),
        ),
    ]
