# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 08:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player_acct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo', models.IntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 16, 8, 15, 11, 258054))),
                ('end_timestamp', models.DateTimeField(blank=True, default=None)),
                ('is_disputed', models.BooleanField(default=False)),
                ('elo_modifier', models.IntegerField(default=25)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=20)),
                ('description', models.TextField(max_length=200)),
                ('elo', models.IntegerField(default=500)),
                ('is_queued', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status', serialize=False, to='dota_mm.GamePlayer')),
                ('state', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_of', to='dota_mm.GamePlayer'),
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='teams', to='dota_mm.GamePlayer'),
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='matches', to='dota_mm.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dota_mm.Team'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='user_acct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dota_player', to='player_acct.Player'),
        ),
        migrations.AddField(
            model_name='status',
            name='current_team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_players', to='dota_mm.Team'),
        ),
    ]
