# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_acct', '0002_auto_20161021_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bnet_id',
            field=models.CharField(blank=True, default='null', max_length=19),
        ),
        migrations.AlterField(
            model_name='player',
            name='steam_id',
            field=models.CharField(blank=True, default='null', max_length=29),
        ),
    ]
